[package]
name = "venice"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
const_format = "0.2.34"
directories = "6.0.0"
miette = { version = "7.6.0", features = ["fancy"] }
rand = "0.9.1"
regex = "1.11.1"
reqwest = "0.12.22"
semver = "1.0.26"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = { version = "1.45.1", features = ["full"] }
toml = "0.8.23"
vex-v5-serial = "0.3.3"
xxhash-rust = { version = "0.8.15", features = ["xxh32"] }

[dependencies.venice-program-table]
git = "https://github.com/venice-v5/venice-program-table.git"
rev = "2fa8d392bb45a7b69e93f5a7e668ad4bca18007d"
features = ["builder"]
